config/routes.rb
Rails.application.routes.draw do
  resources :priority_conditions

  resources :developers

  resources :manufacturers

  resources :topics

   root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:priorityConditionID, :topicTitle, :intervention, :phase, :priorityConditionID, :phaseDetails, :comparators, :healthImpact, :patientPopulation, :status)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :priorityConditionID %><br>
    <%= f.number_field :priorityConditionID %>
  </div>
  <div class="field">
    <%= f.label :topicTitle %><br>
    <%= f.text_field :topicTitle %>
  </div>
  <div class="field">
    <%= f.label :intervention %><br>
    <%= f.text_field :intervention %>
  </div>
  <div class="field">
    <%= f.label :phase %><br>
    <%= f.number_field :phase %>
  </div>
  <div class="field">
    <%= f.label :phaseDetails %><br>
    <%= f.text_field :phaseDetails %>
  </div>
  <div class="field">
    <%= f.label :comparators %><br>
    <%= f.text_field :comparators %>
  </div>
  <div class="field">
    <%= f.label :healthImpact %><br>
    <%= f.text_field :healthImpact %>
  </div>
  <div class="field">
    <%= f.label :patientPopulation %><br>
    <%= f.text_field :patientPopulation %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Priorityconditionid</th>
      <th>Topictitle</th>
      <th>Intervention</th>
      <th>Phase</th>
      <th>Phasedetails</th>
      <th>Comparators</th>
      <th>Healthimpact</th>
      <th>Patientpopulation</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.priorityConditionID %></td>
        <td><%= topic.topicTitle %></td>
        <td><%= topic.intervention %></td>
        <td><%= topic.phase %></td>
        <td><%= topic.phaseDetails %></td>
        <td><%= topic.comparators %></td>
        <td><%= topic.healthImpact %></td>
        <td><%= topic.patientPopulation %></td>
        <td><%= topic.status %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Priorityconditionid:</strong>
  <%= @topic.priorityConditionID %>
</p>

<p>
  <strong>Topictitle:</strong>
  <%= @topic.topicTitle %>
</p>

<p>
  <strong>Intervention:</strong>
  <%= @topic.intervention %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @topic.phase %>
</p>

<p>
  <strong>Phasedetails:</strong>
  <%= @topic.phaseDetails %>
</p>

<p>
  <strong>Comparators:</strong>
  <%= @topic.comparators %>
</p>

<p>
  <strong>Healthimpact:</strong>
  <%= @topic.healthImpact %>
</p>

<p>
  <strong>Patientpopulation:</strong>
  <%= @topic.patientPopulation %>
</p>

<p>
  <strong>Status:</strong>
  <%= @topic.status %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>