config/routes.rb
Rails.application.routes.draw do
  resources :priority_conditions

  resources :developers

  resources :manufacturers

  resources :topics

   root 'topics#index'

end

app/models/priority_condition.rb
class PriorityCondition < ActiveRecord::Base

	validates :name, presence: true

end

app/controllers/priority_conditions_controller.rb
class PriorityConditionsController < ApplicationController
  before_action :set_priority_condition, only: [:show, :edit, :update, :destroy]

  # GET /priority_conditions
  # GET /priority_conditions.json
  def index
    @priority_conditions = PriorityCondition.all
  end

  # GET /priority_conditions/1
  # GET /priority_conditions/1.json
  def show
  end

  # GET /priority_conditions/new
  def new
    @priority_condition = PriorityCondition.new
  end

  # GET /priority_conditions/1/edit
  def edit
  end

  # POST /priority_conditions
  # POST /priority_conditions.json
  def create
    @priority_condition = PriorityCondition.new(priority_condition_params)

    respond_to do |format|
      if @priority_condition.save
        format.html { redirect_to @priority_condition, notice: 'Priority condition was successfully created.' }
        format.json { render :show, status: :created, location: @priority_condition }
      else
        format.html { render :new }
        format.json { render json: @priority_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /priority_conditions/1
  # PATCH/PUT /priority_conditions/1.json
  def update
    respond_to do |format|
      if @priority_condition.update(priority_condition_params)
        format.html { redirect_to @priority_condition, notice: 'Priority condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @priority_condition }
      else
        format.html { render :edit }
        format.json { render json: @priority_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priority_conditions/1
  # DELETE /priority_conditions/1.json
  def destroy
    @priority_condition.destroy
    respond_to do |format|
      format.html { redirect_to priority_conditions_url, notice: 'Priority condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_priority_condition
      @priority_condition = PriorityCondition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def priority_condition_params
      params.require(:priority_condition).permit(:name)
    end
end

app/helpers/priority_conditions_helper.rb
module PriorityConditionsHelper
end

app/views/priority_conditions/_form.html.erb
<%= form_for(@priority_condition) do |f| %>
  <% if @priority_condition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@priority_condition.errors.count, "error") %> prohibited this priority_condition from being saved:</h2>

      <ul>
      <% @priority_condition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priority_conditions/edit.html.erb
<h1>Editing priority_condition</h1>

<%= render 'form' %>

<%= link_to 'Show', @priority_condition %> |
<%= link_to 'Back', priority_conditions_path %>

app/views/priority_conditions/index.html.erb
<h1>Listing priority_conditions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @priority_conditions.each do |priority_condition| %>
      <tr>
        <td><%= priority_condition.name %></td>
        <td><%= link_to 'Show', priority_condition %></td>
        <td><%= link_to 'Edit', edit_priority_condition_path(priority_condition) %></td>
        <td><%= link_to 'Destroy', priority_condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Priority condition', new_priority_condition_path %>

app/views/priority_conditions/new.html.erb
<h1>New priority_condition</h1>

<%= render 'form' %>

<%= link_to 'Back', priority_conditions_path %>

app/views/priority_conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @priority_condition.name %>
</p>

<%= link_to 'Edit', edit_priority_condition_path(@priority_condition) %> |
<%= link_to 'Back', priority_conditions_path %>