config/routes.rb
Rails.application.routes.draw do
  resources :priority_conditions

  resources :developers

  resources :manufacturers

  resources :topics

   root 'topics#index'

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :location, presence: true


end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1
  # PATCH/PUT /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: 'Manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :location)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<%= form_for(@manufacturer) do |f| %>
  <% if @manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% @manufacturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manufacturers/edit.html.erb
<h1>Editing manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @manufacturer %> |
<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/index.html.erb
<h1>Listing manufacturers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manufacturers.each do |manufacturer| %>
      <tr>
        <td><%= manufacturer.name %></td>
        <td><%= manufacturer.location %></td>
        <td><%= link_to 'Show', manufacturer %></td>
        <td><%= link_to 'Edit', edit_manufacturer_path(manufacturer) %></td>
        <td><%= link_to 'Destroy', manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufacturer', new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>New manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manufacturer.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @manufacturer.location %>
</p>

<%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %> |
<%= link_to 'Back', manufacturers_path %>